/**
 * Sitemap Generator
 * 
 * Generates multilingual sitemaps following SEO best practices:
 * - sitemap.xml (index)
 * - sitemap-games-<locale>.xml
 * - sitemap-creators-<locale>.xml
 * - sitemap-lp-<locale>.xml
 */

import { MetadataRoute } from 'next';
import { routing } from '@/i18n/routing';

const baseUrl = process.env.NEXT_PUBLIC_BASE_URL || 'https://strike.gg';

/**
 * Main sitemap index
 */
export default function sitemap(): MetadataRoute.Sitemap {
  const sitemaps: MetadataRoute.Sitemap = [];

  // Static pages
  const staticPages = [
    '',
    '/feed',
    '/games',
    '/clips',
    '/live',
    '/pricing',
    '/auth/login',
    '/auth/register',
  ];

  // Add static pages for all locales
  for (const locale of routing.locales) {
    for (const page of staticPages) {
      const path = locale === routing.defaultLocale ? page : `/${locale}${page}`;
      sitemaps.push({
        url: `${baseUrl}${path}`,
        lastModified: new Date(),
        changeFrequency: page === '' ? 'daily' : 'weekly',
        priority: page === '' ? 1.0 : 0.8,
      });
    }
  }

  // Add sitemap references for dynamic content (Master Prompt Section 10)
  // These are generated by seo-indexer-service and served via Next.js routes
  for (const locale of routing.locales) {
    sitemaps.push({
      url: `${baseUrl}/sitemap-games-${locale}.xml`,
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 0.9,
    });
    sitemaps.push({
      url: `${baseUrl}/sitemap-creators-${locale}.xml`,
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 0.8,
    });
    sitemaps.push({
      url: `${baseUrl}/sitemap-clips-${locale}.xml`,
      lastModified: new Date(),
      changeFrequency: 'hourly', // Clips are updated frequently
      priority: 0.7,
    });
    sitemaps.push({
      url: `${baseUrl}/sitemap-lp-${locale}.xml`,
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.6,
    });
  }

  return sitemaps;
}

/**
 * Generate sitemap for games
 * 
 * This would be called from /sitemap-games-[locale].xml route
 */
export async function generateGamesSitemap(locale: string): Promise<MetadataRoute.Sitemap> {
  const sitemaps: MetadataRoute.Sitemap = [];

  // TODO: Fetch games from game-service
  // const games = await fetchGames({ locale });

  // For Phase 9, return empty (will be populated when games are available)
  // Example structure:
  // for (const game of games) {
  //   const path = locale === routing.defaultLocale
  //     ? `/games/${game.slug}`
  //     : `/${locale}/games/${game.slug}`;
  //   sitemaps.push({
  //     url: `${baseUrl}${path}`,
  //     lastModified: game.updatedAt,
  //     changeFrequency: 'weekly',
  //     priority: 0.9,
  //   });
  // }

  return sitemaps;
}

/**
 * Generate sitemap for creators
 */
export async function generateCreatorsSitemap(locale: string): Promise<MetadataRoute.Sitemap> {
  const sitemaps: MetadataRoute.Sitemap = [];

  // TODO: Fetch creators from creator-service
  // const creators = await fetchCreators({ locale });

  return sitemaps;
}

/**
 * Generate sitemap for clips/reels (Master Prompt Section 10)
 */
export async function generateClipsSitemap(locale: string): Promise<MetadataRoute.Sitemap> {
  const sitemaps: MetadataRoute.Sitemap = [];

  // TODO: Fetch clips from clip-service
  // const clips = await fetchClips({ locale, status: 'published' });
  // 
  // For Phase 7, return empty (will be populated when clips are available)
  // Example structure:
  // for (const clip of clips) {
  //   const path = locale === routing.defaultLocale
  //     ? `/clips/${clip.id}`
  //     : `/${locale}/clips/${clip.id}`;
  //   sitemaps.push({
  //     url: `${baseUrl}${path}`,
  //     lastModified: clip.updatedAt,
  //     changeFrequency: 'daily',
  //     priority: 0.7,
  //   });
  // }

  return sitemaps;
}

/**
 * Generate sitemap for landing pages
 */
export async function generateLandingPagesSitemap(
  locale: string
): Promise<MetadataRoute.Sitemap> {
  const sitemaps: MetadataRoute.Sitemap = [];

  // TODO: Fetch landing pages from campaign config
  // const landingPages = await fetchLandingPages({ locale });

  return sitemaps;
}

